local awful = require("awful")
local Window = require("ui.dock.window")
local gtimer = require("gears.timer")

gtimer.delayed_call(function()
  awful.screen.connect_for_each_screen(function(s)
    s.dock = Window(s)
    s.dock:raise()
  end)
end)
